server:
  port: 0
  tomcat:
    relaxed-query-chars: '|,{,},[,]'

spring:
  application:
    name: shopping-store
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    username: smart
    password: secret
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/smart